spring:
  datasource:
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?useSSL=false&serverTimezone=UTC
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8080
